"""
SaleFlex.PyPOS - Point of Sale Application

Copyright (c) 2025 Ferhat Mousavi (ferhat.mousavi@gmail.com)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from sqlalchemy.orm import Session
from data_layer.model.definition.form import Form
from data_layer.model.definition.form_control import FormControl
from data_layer.enums import ControlName, EventName


def _insert_form_controls(session: Session, cashier_id: str):
    """
    Insert initial form controls for login and sale forms.
    
    Args:
        session: Database session
        cashier_id: ID of the cashier creating the records
    """
    # Check if form controls already exist
    if session.query(FormControl).count() > 0:
        return
    
    # Get form IDs
    login_form = session.query(Form).filter(Form.form_no == 1).first()
    sale_form = session.query(Form).filter(Form.form_no == 2).first()
    
    if not login_form or not sale_form:
        print("⚠ Forms not found. Cannot insert form controls.")
        return
    
    # Get form IDs for navigation
    sale_form_id = sale_form.id
    
    # Login form controls
    # Using ControlName and EventName enums for consistency
    login_form_controls = [
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.CASHIER_NAME_LIST.value,  # Special name for auto-loading cashiers
            form_control_function1=EventName.LOGIN.value,  # Used to add SUPERVISOR option
            form_control_function2=None,
            type_no=3,
            type="COMBOBOX",
            width=300,
            height=50,
            location_x=362,
            location_y=150,
            start_position=None,
            caption1="Select Cashier",
            caption2=None,
            list_values=None,  # Auto-populated from database
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Select your name from the list",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.PASSWORD.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=50,
            location_x=362,
            location_y=225,
            start_position=None,
            caption1="Password",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter your password",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="PASSWORD",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.LOGIN.value,
            form_control_function1=EventName.LOGIN.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=300,
            height=50,
            location_x=362,
            location_y=300,
            start_position=None,
            caption1="LOGIN",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x003366",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            # fk_target_form_id removed - LOGIN event handler handles navigation after successful login
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.EXIT.value,
            form_control_function1=EventName.EXIT_APPLICATION.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=300,
            height=50,
            location_x=362,
            location_y=375,
            start_position=None,
            caption1="EXIT",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Exit Application",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF0000",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Sale form controls
    sale_form_controls = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="SALESLIST",
            form_control_function1=EventName.SALE_OPTION.value,
            form_control_function2=None,
            type_no=4,
            type="SALESLIST",
            width=755,
            height=250,
            location_x=252,
            location_y=1,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="NUMPAD",
            form_control_function1=EventName.SALE_PLU_BARCODE.value,
            form_control_function2=None,
            type_no=5,
            type="NUMPAD",
            width=230,
            height=298,
            location_x=778,
            location_y=404,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENTLIST",
            form_control_function1="PAYMENTLIST",  # Custom control, not an event
            form_control_function2=None,
            type_no=6,
            type="PAYMENTLIST",
            width=230,
            height=298,
            location_x=547,
            location_y=404,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="AMOUNTSTABLE",
            form_control_function1="AMOUNTSTABLE",  # Custom control, not an event
            form_control_function2=None,
            type_no=7,
            type="AMOUNTSTABLE",
            width=250,
            height=200,
            location_x=1,
            location_y=1,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CLOSURE",
            form_control_function1=EventName.CLOSURE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=1,
            location_y=603,
            start_position=None,
            caption1="CLOSURE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="RED",
            fore_color="WHITE",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="EXIT",
            form_control_function1=EventName.EXIT_APPLICATION.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=126,
            location_y=603,
            start_position=None,
            caption1="EXIT",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Department buttons
    department_buttons = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="DEPARTMENT1",
            form_control_function1=EventName.SALE_DEPARTMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=1,
            location_y=202,
            start_position=None,
            caption1="FOOD",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="DEPARTMENT2",
            form_control_function1=EventName.SALE_DEPARTMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=1,
            location_y=303,
            start_position=None,
            caption1="TOBACCO",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="DEPARTMENT3",
            form_control_function1=EventName.SALE_DEPARTMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=1,
            location_y=404,
            start_position=None,
            caption1="INDIVIDUAL",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # PLU buttons
    plu_buttons = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PLU1",
            form_control_function1=EventName.SALE_PLU_CODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=126,
            location_y=202,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PLU2",
            form_control_function1=EventName.SALE_PLU_CODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=126,
            location_y=303,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PLU3",
            form_control_function1=EventName.SALE_PLU_CODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=126,
            location_y=404,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Product barcode buttons
    product_barcode_buttons = [
        ("PLU5000157070008", 252, 252),
        ("PLU7622210449283", 360, 252),
        ("PLU5000328721575", 468, 252),
        ("PLU8711200334532", 576, 252),
        ("PLU5449000000996", 684, 252),
        ("PLU0746817004304", 792, 252),
        ("PLU7622210700394", 900, 252),
        ("PLU5000328355037", 252, 327),
        ("PLU5000157077916", 360, 327),
        ("PLU5010044003089", 468, 327),
        ("PLU5740900802725", 576, 327),
        ("PLU8001090390021", 684, 327),
        ("PLU8714100852703", 792, 327),
        ("PLU5000171054815", 900, 327)
    ]
    
    product_controls = []
    for plu_name, x, y in product_barcode_buttons:
        height = 75 if y == 252 else 76
        product_controls.append(
            FormControl(
                fk_form_id=sale_form.id,
                fk_parent_id=None,
                name=plu_name,
                form_control_function1=EventName.SALE_PLU_BARCODE.value,
                form_control_function2=None,
                type_no=1,
                type="BUTTON",
                width=107,
                height=height,
                location_x=x,
                location_y=y,
                start_position=None,
                caption1="",
                caption2=None,
                list_values=None,
                dock=None,
                alignment=None,
                text_alignment="CENTER",
                character_casing="UPPER",
                font="Tahoma",
                icon=None,
                tool_tip=None,
                image=None,
                image_selected=None,
                font_auto_height=False,
                font_size=12,
                input_type="ALPHANUMERIC",
                text_image_relation=None,
                back_color=None,
                fore_color=None,
                keyboard_value=None,
                fk_cashier_create_id=cashier_id,
                fk_cashier_update_id=cashier_id
            )
        )
    
    # Cash payment buttons
    cash_payment_buttons = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH2000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=98,
            location_x=251,
            location_y=404,
            start_position=None,
            caption1="20 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH5000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=99,
            location_x=251,
            location_y=503,
            start_position=None,
            caption1="50 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH10000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=99,
            location_x=251,
            location_y=603,
            start_position=None,
            caption1="100 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENT_CASH",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=150,
            height=187,
            location_x=396,
            location_y=404,
            start_position=None,
            caption1="CASH",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENT_CREDIT",
            form_control_function1=EventName.CREDIT_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=150,
            height=110,
            location_x=396,
            location_y=592,
            start_position=None,
            caption1="CREDIT CARD",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Combine all controls
    all_controls = (
        login_form_controls + 
        sale_form_controls + 
        department_buttons + 
        plu_buttons + 
        product_controls + 
        cash_payment_buttons
    )
    
    # Add all controls to session
    for control in all_controls:
        session.add(control)
    
    session.commit()
    print(f"✓ {len(all_controls)} form controls inserted successfully") 