"""
SaleFlex.PyPOS - Point of Sale Application

Copyright (c) 2025 Ferhat Mousavi

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from sqlalchemy.orm import Session
from data_layer.model.definition.form import Form
from data_layer.model.definition.form_control import FormControl
from data_layer.enums import ControlName, EventName


def _insert_form_controls(session: Session, cashier_id: str):
    """
    Insert initial form controls for login and sale forms.
    
    Args:
        session: Database session
        cashier_id: ID of the cashier creating the records
    """
    # Check if form controls already exist
    if session.query(FormControl).count() > 0:
        return
    
    # Get form IDs
    login_form = session.query(Form).filter(Form.form_no == 1).first()
    main_menu_form = session.query(Form).filter(Form.form_no == 2).first()
    config_form = session.query(Form).filter(Form.form_no == 3).first()
    cashier_form = session.query(Form).filter(Form.form_no == 4).first()
    sale_form = session.query(Form).filter(Form.form_no == 5).first()
    closure_form = session.query(Form).filter(Form.form_no == 6).first()
    
    if not login_form or not sale_form or not main_menu_form or not config_form or not cashier_form or not closure_form:
        print("⚠ Forms not found. Cannot insert form controls.")
        return
    
    # Login form controls
    # Using ControlName and EventName enums for consistency
    login_form_controls = [
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.CASHIER_NAME_LIST.value,  # Special name for auto-loading cashiers
            form_control_function1=EventName.LOGIN.value,  # Used to add SUPERVISOR option
            form_control_function2=None,
            type_no=3,
            type="COMBOBOX",
            width=300,
            height=50,
            location_x=362,
            location_y=150,
            start_position=None,
            caption1="Select Cashier",
            caption2=None,
            list_values=None,  # Auto-populated from database
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Select your name from the list",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.PASSWORD.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=50,
            location_x=362,
            location_y=225,
            start_position=None,
            caption1="Password",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter your password",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="PASSWORD",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.LOGIN.value,
            form_control_function1=EventName.LOGIN.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=300,
            height=50,
            location_x=362,
            location_y=300,
            start_position=None,
            caption1="LOGIN",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x003366",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=login_form.id,
            fk_parent_id=None,
            name=ControlName.EXIT.value,
            form_control_function1=EventName.EXIT_APPLICATION.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=300,
            height=50,
            location_x=362,
            location_y=375,
            start_position=None,
            caption1="EXIT",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Exit Application",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF0000",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Sale form controls
    sale_form_controls = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="SALESLIST",
            form_control_function1=EventName.SALE_OPTION.value,
            form_control_function2=None,
            type_no=4,
            type="SALESLIST",
            width=769,
            height=250,
            location_x=252,
            location_y=1,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="NUMPAD",
            form_control_function1=EventName.SALE_PLU_BARCODE.value,
            form_control_function2=None,
            type_no=5,
            type="NUMPAD",
            width=242,
            height=338,
            location_x=779,
            location_y=404,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENTLIST",
            form_control_function1="PAYMENTLIST",  # Custom control, not an event
            form_control_function2=None,
            type_no=6,
            type="PAYMENTLIST",
            width=230,
            height=338,
            location_x=547,
            location_y=404,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="AMOUNTSTABLE",
            form_control_function1="AMOUNTSTABLE",  # Custom control, not an event
            form_control_function2=None,
            type_no=7,
            type="AMOUNTSTABLE",
            width=250,
            height=213,
            location_x=1,
            location_y=1,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="BACK",
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=113,
            location_x=1,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xD3D3D3",  # Light Gray
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Department buttons
    department_buttons = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="DEPARTMENT1",
            form_control_function1=EventName.SALE_DEPARTMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=1,
            location_y=215,
            start_position=None,
            caption1="FOOD",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x98FB98",  # Pale Green
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="DEPARTMENT2",
            form_control_function1=EventName.SALE_DEPARTMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=1,
            location_y=316,
            start_position=None,
            caption1="TOBACCO",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x98FB98",  # Pale Green
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="DEPARTMENT3",
            form_control_function1=EventName.SALE_DEPARTMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=1,
            location_y=417,
            start_position=None,
            caption1="INDIVIDUAL",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x98FB98",  # Pale Green
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # PLU buttons
    plu_buttons = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PLU1",
            form_control_function1=EventName.SALE_PLU_CODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=126,
            location_y=215,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFE4B5",  # Moccasin
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PLU2",
            form_control_function1=EventName.SALE_PLU_CODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=100,
            location_x=126,
            location_y=316,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFE4B5",  # Moccasin
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PLU3",
            form_control_function1=EventName.SALE_PLU_CODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=126,
            location_y=417,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFE4B5",  # Moccasin
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Product barcode buttons
    product_barcode_buttons = [
        ("PLU5000157070008", 252, 252),
        ("PLU7622210449283", 362, 252),
        ("PLU5000328721575", 472, 252),
        ("PLU8711200334532", 582, 252),
        ("PLU5449000000996", 692, 252),
        ("PLU0746817004304", 802, 252),
        ("PLU7622210700394", 912, 252),
        ("PLU5000328355037", 252, 327),
        ("PLU5000157077916", 362, 327),
        ("PLU5010044003089", 472, 327),
        ("PLU5740900802725", 582, 327),
        ("PLU8001090390021", 692, 327),
        ("PLU8714100852703", 802, 327),
        ("PLU5000171054815", 912, 327)
    ]
    
    product_controls = []
    for plu_name, x, y in product_barcode_buttons:
        height = 75 if y == 252 else 76
        product_controls.append(
            FormControl(
                fk_form_id=sale_form.id,
                fk_parent_id=None,
                name=plu_name,
                form_control_function1=EventName.SALE_PLU_BARCODE.value,
                form_control_function2=None,
                type_no=1,
                type="BUTTON",
                width=109,
                height=height,
                location_x=x,
                location_y=y,
                start_position=None,
                caption1="",
                caption2=None,
                list_values=None,
                dock=None,
                alignment=None,
                text_alignment="CENTER",
                character_casing="UPPER",
                font="Tahoma",
                icon=None,
                tool_tip=None,
                image=None,
                image_selected=None,
                font_auto_height=True,
                font_size=12,
                input_type="ALPHANUMERIC",
                text_image_relation=None,
                back_color="0xFFB6C1",  # Light Pink
                fore_color="0x000000",
                keyboard_value=None,
                fk_cashier_create_id=cashier_id,
                fk_cashier_update_id=cashier_id
            )
        )
    
    # Cash payment buttons
    cash_payment_buttons = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH2000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=113,
            location_x=251,
            location_y=404,
            start_position=None,
            caption1="20 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x87CEEB",  # Sky Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH5000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=113,
            location_x=251,
            location_y=517,
            start_position=None,
            caption1="50 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x87CEEB",  # Sky Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH10000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=113,
            location_x=251,
            location_y=630,
            start_position=None,
            caption1="100 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x87CEEB",  # Sky Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENT_CASH",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=150,
            height=187,
            location_x=396,
            location_y=404,
            start_position=None,
            caption1="CASH",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x90EE90",  # Light Green
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENT_CREDIT",
            form_control_function1=EventName.CREDIT_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=150,
            height=151,
            location_x=396,
            location_y=592,
            start_position=None,
            caption1="CREDIT CARD",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xDDA0DD",  # Plum
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CHANGE",
            form_control_function1=EventName.CHANGE_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=113,
            location_x=126,
            location_y=630,
            start_position=None,
            caption1="Change",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="SUBTOTAL",
            form_control_function1=EventName.SUBTOTAL.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=250,
            height=113,
            location_x=1,
            location_y=517,
            start_position=None,
            caption1="SUB TOTAL",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x2F4F4F",  # Dark Slate Gray
            fore_color="0xFFFFFF",  # White
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Main Menu form controls
    main_menu_form_controls = [
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_SALE",
            form_control_function1=EventName.SALES_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=150,
            start_position=None,
            caption1="SALES",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Sales Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x228B22",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_CLOSURE",
            form_control_function1=EventName.CLOSURE_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=250,
            start_position=None,
            caption1="CLOSURE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Closure Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xDC143C",  # Crimson - distinctive color for closure operation
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_CONFIG",
            form_control_function1=EventName.SETTING_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=350,
            start_position=None,
            caption1="SETTINGS",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Settings Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_CASHIER",
            form_control_function1=EventName.CASHIER_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=450,
            start_position=None,
            caption1="CASHIER MANAGEMENT",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Cashier Management Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF8C00",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name=ControlName.LOGOUT.value,
            form_control_function1=EventName.LOGOUT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="LOGOUT",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Exit current user session",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Configuration form controls
    # First create the Panel control (name matches model name)
    config_panel = FormControl(
        fk_form_id=config_form.id,
        fk_parent_id=None,
        name="POS_SETTINGS",  # Model name in uppercase
        form_control_function1=None,
        form_control_function2=None,
        type_no=10,  # New type number for Panel
        type="PANEL",
        width=900,
        height=550,
        location_x=62,
        location_y=50,
        start_position=None,
        caption1="POS Settings",
        caption2=None,
        list_values=None,
        dock=None,
        alignment=None,
        text_alignment="CENTER",
        character_casing="NORMAL",
        font="Tahoma",
        icon=None,
        tool_tip="POS Settings Configuration Panel",
        image=None,
        image_selected=None,
        font_auto_height=False,
        font_size=0,
        input_type="ALPHANUMERIC",
        text_image_relation=None,
        back_color="0x2F4F4F",
        fore_color="0xFFFFFF",
        keyboard_value=None,
        fk_cashier_create_id=cashier_id,
        fk_cashier_update_id=cashier_id
    )
    
    # Store panel ID for child controls (will be set after panel is added to session)
    # For now, we'll use a placeholder and update after panel creation
    config_panel_id_placeholder = None  # Will be set after panel is created
    
    # PosSettings field controls - all will be children of the panel
    # Field definitions with labels and field names (field names match model attributes)
    pos_settings_fields = [
        ("POS No in Store", "pos_no_in_store", "NUMERIC"),
        ("Name", "name", "ALPHANUMERIC"),
        ("Owner National ID", "owner_national_id", "ALPHANUMERIC"),
        ("Owner Tax ID", "owner_tax_id", "ALPHANUMERIC"),
        ("Owner Web Address", "owner_web_address", "ALPHANUMERIC"),
        ("MAC Address", "mac_address", "ALPHANUMERIC"),
        ("Customer Display Type", "customer_display_type", "ALPHANUMERIC"),
        ("Customer Display Port", "customer_display_port", "ALPHANUMERIC"),
        ("Receipt Printer Type", "receipt_printer_type", "ALPHANUMERIC"),
        ("Receipt Printer Port", "receipt_printer_port", "ALPHANUMERIC"),
        ("Invoice Printer Type", "invoice_printer_type", "ALPHANUMERIC"),
        ("Invoice Printer Port", "invoice_printer_port", "ALPHANUMERIC"),
        ("Scale Type", "scale_type", "ALPHANUMERIC"),
        ("Scale Port", "scale_port", "ALPHANUMERIC"),
        ("Barcode Reader Port", "barcode_reader_port", "ALPHANUMERIC"),
        ("Backend IP 1", "backend_ip1", "ALPHANUMERIC"),
        ("Backend Port 1", "backend_port1", "NUMERIC"),
        ("Backend IP 2", "backend_ip2", "ALPHANUMERIC"),
        ("Backend Port 2", "backend_port2", "NUMERIC"),
        ("Backend Type", "backend_type", "ALPHANUMERIC"),
        ("Device Serial Number", "device_serial_number", "ALPHANUMERIC"),
        ("Device OS", "device_operation_system", "ALPHANUMERIC"),
        ("Force Online", "force_to_work_online", "ALPHANUMERIC"),  # Boolean - will be checkbox later
        ("PLU Update No", "plu_update_no", "NUMERIC"),
    ]
    
    # Create label and textbox pairs for each field
    pos_settings_controls = []
    start_y = 20  # Starting Y position inside panel
    label_width = 200
    textbox_width = 400
    control_height = 40
    spacing = 10
    row_height = control_height + spacing
    
    for i, (label_text, field_name, input_type) in enumerate(pos_settings_fields):
        y_pos = start_y + (i * row_height)
        
        # Label
        label_control = FormControl(
            fk_form_id=config_form.id,
            fk_parent_id=None,  # Will be set to panel ID after panel is created
            parent_name="POS_SETTINGS",  # Panel name matches model name
            name=f"LBL_{field_name.upper()}",
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=8,
            type="LABEL",
            width=label_width,
            height=control_height,
            location_x=10,
            location_y=y_pos,
            start_position=None,
            caption1=label_text + ":",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="RIGHT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
        pos_settings_controls.append(label_control)
        
        # TextBox - name is uppercase but lower() gives model field name
        # e.g., "POS_NO_IN_STORE" -> lower() -> "pos_no_in_store" (matches model attribute)
        textbox_control = FormControl(
            fk_form_id=config_form.id,
            fk_parent_id=None,  # Will be set to panel ID after panel is created
            parent_name="POS_SETTINGS",  # Panel name matches model name
            name=field_name.upper(),  # Uppercase name, but lower() gives model field name
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=textbox_width,
            height=control_height,
            location_x=label_width + 20,
            location_y=y_pos,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=f"Enter {label_text.lower()}",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type=input_type,
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
        pos_settings_controls.append(textbox_control)
    
    # SAVE button (outside panel)
    save_button = FormControl(
        fk_form_id=config_form.id,
        fk_parent_id=None,
        name=ControlName.SAVE.value,
        form_control_function1=EventName.SAVE_CHANGES.value,
        form_control_function2=None,
        type_no=1,
        type="BUTTON",
        width=125,
        height=99,
        location_x=745,
        location_y=630,
        start_position=None,
        caption1="SAVE",
        caption2=None,
        list_values=None,
        dock=None,
        alignment=None,
        text_alignment="CENTER",
        character_casing="UPPER",
        font="Tahoma",
        icon=None,
        tool_tip="Save POS Settings",
        image=None,
        image_selected=None,
        font_auto_height=False,
        font_size=14,
        input_type="ALPHANUMERIC",
        text_image_relation=None,
        back_color="0x228B22",  # Forest Green for save action
        fore_color="0xFFFFFF",
        keyboard_value=None,
        fk_cashier_create_id=cashier_id,
        fk_cashier_update_id=cashier_id
    )
    
    # BACK button (outside panel)
    back_button = FormControl(
        fk_form_id=config_form.id,
        fk_parent_id=None,
        name=ControlName.BACK.value,
        form_control_function1=EventName.BACK.value,
        form_control_function2=None,
        type_no=1,
        type="BUTTON",
        width=125,
        height=99,
        location_x=880,
        location_y=630,
        start_position=None,
        caption1="BACK",
        caption2=None,
        list_values=None,
        dock=None,
        alignment=None,
        text_alignment="CENTER",
        character_casing="UPPER",
        font="Tahoma",
        icon=None,
        tool_tip="Back to Main Menu",
        image=None,
        image_selected=None,
        font_auto_height=False,
        font_size=14,
        input_type="ALPHANUMERIC",
        text_image_relation=None,
        back_color="0x4682B4",
        fore_color="0xFFFFFF",
        keyboard_value=None,
        fk_cashier_create_id=cashier_id,
        fk_cashier_update_id=cashier_id
    )
    
    # Combine all config form controls
    config_form_controls = [config_panel] + pos_settings_controls + [save_button, back_button]
    
    # After panel is added to session, update child controls' fk_parent_id
    # Note: This will be done after adding to session and committing to get the panel ID
    
    # Cashier form controls
    cashier_form_controls = [
        # Username label and textbox
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name="LBL_USERNAME",
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=8,
            type="LABEL",
            width=150,
            height=40,
            location_x=200,
            location_y=150,
            start_position=None,
            caption1="Username:",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="RIGHT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.CASHIER_NAME.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=40,
            location_x=370,
            location_y=150,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter cashier username",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Name label and textbox
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name="LBL_NAME",
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=8,
            type="LABEL",
            width=150,
            height=40,
            location_x=200,
            location_y=210,
            start_position=None,
            caption1="Name:",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="RIGHT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.NAME.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=40,
            location_x=370,
            location_y=210,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter cashier first name",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Last Name label and textbox
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name="LBL_LAST_NAME",
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=8,
            type="LABEL",
            width=150,
            height=40,
            location_x=200,
            location_y=270,
            start_position=None,
            caption1="Last Name:",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="RIGHT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.LAST_NAME.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=40,
            location_x=370,
            location_y=270,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter cashier last name",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Password label and textbox
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name="LBL_PASSWORD",
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=8,
            type="LABEL",
            width=150,
            height=40,
            location_x=200,
            location_y=330,
            start_position=None,
            caption1="Password:",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="RIGHT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.PASSWORD.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=40,
            location_x=370,
            location_y=330,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter cashier password",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="PASSWORD",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # ID Number label and textbox
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name="LBL_ID_NUMBER",
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=8,
            type="LABEL",
            width=150,
            height=40,
            location_x=200,
            location_y=390,
            start_position=None,
            caption1="ID Number:",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="RIGHT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.ID_NUMBER.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=40,
            location_x=370,
            location_y=390,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter cashier ID number",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Description label and textbox
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name="LBL_DESCRIPTION",
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=8,
            type="LABEL",
            width=150,
            height=40,
            location_x=200,
            location_y=450,
            start_position=None,
            caption1="Description:",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="RIGHT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.DESCRIPTION.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=2,
            type="TEXTBOX",
            width=300,
            height=40,
            location_x=370,
            location_y=450,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Enter additional description",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Save button
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.SAVE.value,
            form_control_function1=EventName.SAVE_CHANGES.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=745,
            location_y=630,
            start_position=None,
            caption1="SAVE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Save cashier information",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x228B22",  # Forest Green for save action
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Back button
        FormControl(
            fk_form_id=cashier_form.id,
            fk_parent_id=None,
            name=ControlName.BACK.value,
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Back to Main Menu",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Closure form controls
    closure_form_controls = [
        # DataGrid to display previous closures
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name=ControlName.DATAGRID.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=9,
            type="DATAGRID",
            width=900,
            height=400,
            location_x=62,
            location_y=50,
            start_position=None,
            caption1="Closure History",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Previous closure records",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Closure button (moved down)
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name=ControlName.CLOSURE.value,
            form_control_function1=EventName.CLOSURE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=480,
            start_position=None,
            caption1="CLOSURE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Execute closure operation",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF0000",  # Red color for closure
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        ),
        # Back button
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name=ControlName.BACK.value,
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Back to Main Menu",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id
        )
    ]
    
    # Combine all controls
    all_controls = (
        login_form_controls + 
        sale_form_controls + 
        department_buttons + 
        plu_buttons + 
        product_controls + 
        cash_payment_buttons +
        main_menu_form_controls +
        config_form_controls +
        cashier_form_controls +
        closure_form_controls
    )
    
    # Add all controls to session
    for control in all_controls:
        session.add(control)
    
    # Flush to get IDs for parent-child relationships
    session.flush()
    
    # Update parent IDs for config form panel children
    # Find the panel control
    config_panel_control = None
    for control in config_form_controls:
        if control.type == "PANEL" and control.name == "POS_SETTINGS":
            config_panel_control = control
            break
    
    if config_panel_control:
        # Update all child controls to reference the panel
        for control in pos_settings_controls:
            if control.parent_name == "POS_SETTINGS":
                control.fk_parent_id = config_panel_control.id
    
    session.commit()
    print(f"✓ {len(all_controls)} form controls inserted successfully") 