[settings]
name = "Sale"
functionality = "SALE"
login_required = true
toolbar = true
statusbar = true
background_color = 0x3268A8
foreground_color = 0x000000
width = 1024
height = 768

[toolbar_settings]
button.back = { caption = "Back", image = "back.png" }

[[design]]
type = "button"
caption = "Back"
function = "BACK"
background_color = 0xFF0000
foreground_color = 0xFFFFFF
width = 200
height = 50
location_x = 412
location_y = 100

[[design]]
type = "numpad"
caption = "NumPad"
function = "PLU"
background_color = 0x778D45
foreground_color = 0xFFFFFF
width = 300
height = 400
location_x = 720
location_y = 340

[[design]]
type = "payment_list"
caption = "PaymentList"
function = "PLU"
background_color = 0x778D45
foreground_color = 0xFFFFFF
width = 400
height = 400
location_x = 315
location_y = 340

[[design]]
type = "sale_list"
caption = "SaleList"
function = "PLU"
background_color = 0x778D45
foreground_color = 0xFFFFFF
width = 400
height = 290
location_x = 620
location_y = 45
