"""
SaleFlex.PyPOS - Point of Sale Application

Copyright (c) 2025 Ferhat Mousavi (ferhat.mousavi@gmail.com)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import enum


class EventName(enum.Enum):
    """Enum representing different event names and custom function names used in the system."""
    NONE = "NONE"
    EXIT_APPLICATION = "EXIT_APPLICATION"
    LOGIN = "LOGIN"
    LOGIN_EXTENDED = "LOGIN_EXTENDED"
    LOGOUT = "LOGOUT"
    SALE = "SALE"                           # General sale event
    CONFIG = "CONFIG"                       # General configuration event  
    BACK = "BACK"                          # General back/return event
    SERVICE_CODE_REQUEST = "SERVICE_CODE_REQUEST"
    LOGIN_SERVICE = "LOGIN_SERVICE"
    CLOSE_FORM = "CLOSE_FORM"
    SAVE_CHANGES = "SAVE_CHANGES"
    SALE_DEPARTMENT = "SALE_DEPARTMENT"
    SALE_DEPARTMENT_BY_NO = "SALE_DEPARTMENT_BY_NO"
    SALE_PLU_CODE = "SALE_PLU_CODE"
    SALE_PLU_BARCODE = "SALE_PLU_BARCODE"
    GET_PLU_FROM_MAINGROUP = "GET_PLU_FROM_MAINGROUP"
    REPEAT_LAST_SALE = "REPEAT_LAST_SALE"
    REPEAT_SALE = "REPEAT_SALE"
    CANCEL_DEPARTMENT = "CANCEL_DEPARTMENT"
    CANCEL_PLU = "CANCEL_PLU"
    CANCEL_LAST_SALE = "CANCEL_LAST_SALE"
    CANCEL_SALE = "CANCEL_SALE"
    OPEN_CASH_DRAWER = "OPEN_CASH_DRAWER"
    FUNCTION_MENU = "FUNCTION_MENU"
    SALES_MENU = "SALES_MENU"
    SERVICE_MENU = "SERVICE_MENU"
    SETTING_MENU = "SETTING_MENU"
    REPORT_MENU = "REPORT_MENU"
    CASHIER = "CASHIER"
    CHANGE_DOCUMENT_TYPE = "CHANGE_DOCUMENT_TYPE"
    CUSTOMER = "CUSTOMER"
    REFUND = "REFUND"
    DISCOUNT_BY_AMOUNT = "DISCOUNT_BY_AMOUNT"
    SURCHARGE_BY_AMOUNT = "SURCHARGE_BY_AMOUNT"
    DISCOUNT_BY_PERCENT = "DISCOUNT_BY_PERCENT"
    SURCHARGE_BY_PERCENT = "SURCHARGE_BY_PERCENT"
    INPUT_PRICE = "INPUT_PRICE"
    INPUT_QUANTITY = "INPUT_QUANTITY"
    INPUT_AMOUNT = "INPUT_AMOUNT"
    PRICE_LOOKUP = "PRICE_LOOKUP"
    SUBTOTAL = "SUBTOTAL"
    TOTAL = "TOTAL"
    SALE_OPTION = "SALE_OPTION"
    CLEAR_BUFFER = "CLEAR_BUFFER"
    PAYMENT = "PAYMENT"                         # Payment Function
    CASH_PAYMENT = "CASH_PAYMENT"                # Payment Function
    CREDIT_PAYMENT = "CREDIT_PAYMENT"            # Payment Function
    CHECK_PAYMENT = "CHECK_PAYMENT"              # Payment Function
    EXCHANGE_PAYMENT = "EXCHANGE_PAYMENT"        # Payment Function
    PREPAID_PAYMENT = "PREPAID_PAYMENT"          # Payment Function
    CHARGE_SALE_PAYMENT = "CHARGE_SALE_PAYMENT"        # Payment Function
    OTHER_PAYMENT = "OTHER_PAYMENT"         # Payment Function
    PAYMENT_DETAIL = "PAYMENT_DETAIL"
    CANCEL_DOCUMENT = "CANCEL_DOCUMENT"
    CLOSURE = "CLOSURE"
    STOCK_ENTRY_FORM = "STOCK_ENTRY_FORM"
    SALE_DETAIL_REPORT = "SALE_DETAIL_REPORT"
    PLU_SALE_REPORT = "PLU_SALE_REPORT"
    POS_SUMMARY_REPORT = "POS_SUMMARY_REPORT"
    SET_DISPLAY_BRIGHTNESS = "SET_DISPLAY_BRIGHTNESS"
    SET_PRINTER_INTENSITY = "SET_PRINTER_INTENSITY"
    SET_CASHIER = "SET_CASHIER"
    SET_SUPERVISOR = "SET_SUPERVISOR"
    SET_RECEIPT_HEADER = "SET_RECEIPT_HEADER"
    SET_RECEIPT_FOOTER = "SET_RECEIPT_FOOTER"
    SET_IDLE_MESSAGE = "SET_IDLE_MESSAGE"
    SET_BARCODE_DEFINITION = "SET_BARCODE_DEFINITION"
    SET_VAT_DEFINITION = "SET_VAT_DEFINITION"
    SET_DEPARTMENT_DEFINITION = "SET_DEPARTMENT_DEFINITION"
    SET_CURRENCY_DEFINITION = "SET_CURRENCY_DEFINITION"
    SET_PLU_DEFINITION = "SET_PLU_DEFINITION"
    SET_PLU_MAINGROUP_DEFINITION = "SET_PLU_MAINGROUP_DEFINITION"
    SET_DISCOUNT_RATE = "SET_DISCOUNT_RATE"
    SET_SURCHARGE_RATE = "SET_SURCHARGE_RATE"
    SERVICE_COMPANY_INFO = "SERVICE_COMPANY_INFO"
    SERVICE_CHANGE_DATE_TIME = "SERVICE_CHANGE_DATE_TIME"
    SERVICE_PARAMETER_DOWNLOAD = "SERVICE_PARAMETER_DOWNLOAD"
    SERVICE_SET_RECEIPT_LIMIT = "SERVICE_SET_RECEIPT_LIMIT"
    SERVICE_RESET_TO_FACTORY_MODE = "SERVICE_RESET_TO_FACTORY_MODE"
    SERVICE_RESET_PASSWORD = "SERVICE_RESET_PASSWORD"
    SERVICE_CHANGE_PASSWORD = "SERVICE_CHANGE_PASSWORD"
    SERVICE_POS_ACTIVE = "SERVICE_POS_ACTIVE"
    SERVICE_SOFTWARE_DOWNLOAD = "SERVICE_SOFTWARE_DOWNLOAD"
    INVOICE_LIST = "INVOICE_LIST"
    WAYBILL_LIST = "WAYBILL_LIST"
    RETURN_LIST = "RETURN_LIST"
    SERVICE_GET_PLU_LIST = "SERVICE_GET_PLU_LIST"
    STOCK_LIST = "STOCK_LIST"
    SUSPEND_PAYMENT = "SUSPEND_PAYMENT"
    BACK_PAYMENT = "BACK_PAYMENT"
    SALE_SHORTCUT = "SALE_SHORTCUT"
    REDRAW_FORM = "REDRAW_FORM" 